apiVersion: v1
kind: PersistentVolume
metadata:
  name: tts-models-pv
  namespace: sesame-tts
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/tts-models
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tts-audio-pv
  namespace: sesame-tts
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/tts-audio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-models-pvc
  namespace: sesame-tts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-audio-pvc
  namespace: sesame-tts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
